class SessionKeys:
      BOOKING_TYPE: str = 'BOOKING_TYPE'
      PENDING_FORM_DATA: str = 'PENDING_FORM_DATA'
      COMPATIBLE_LOAD_IDS: str = 'COMPATIBLE_LOAD_IDS'
      COMPATIBLE_TRUCK_IDS: str = 'COMPATIBLE_TRUCK_IDS'