"""Initial migration

Revision ID: 1f41ab686256
Revises: 
Create Date: 2025-08-17 19:45:41.515603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f41ab686256'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('LOAD',
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('pickup_contact_name', sa.String(), nullable=False),
    sa.Column('pickup_contact_phone', sa.String(), nullable=False),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('drop_contact_name', sa.String(), nullable=False),
    sa.Column('drop_contact_phone', sa.String(), nullable=False),
    sa.Column('drop_address', sa.String(), nullable=False),
    sa.Column('drop_datetime', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.Column('truck', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('load_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('TRUCK',
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('available_locations', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=False),
    sa.Column('owner_aadhaar', sa.String(), nullable=False),
    sa.Column('owner_pan', sa.String(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('driver_aadhaar', sa.String(), nullable=False),
    sa.Column('driver_license', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tds', sa.String(), nullable=False),
    sa.Column('insurance', sa.String(), nullable=False),
    sa.Column('load', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('truck_id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TRUCK')
    op.drop_table('LOAD')
    op.drop_table('USER')
    # ### end Alembic commands ###
