"""updated columns

Revision ID: d29ce5fb84b7
Revises: 
Create Date: 2025-08-29 19:55:13.819333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29ce5fb84b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_fullname', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('user_created_time', sa.DateTime(), nullable=False),
    sa.Column('user_updated_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_password'),
    sa.UniqueConstraint('user_phone')
    )
    op.create_table('TRUCK',
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_registration_number', sa.String(), nullable=False),
    sa.Column('vehicle_model_name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('vehicle_capacity', sa.Float(), nullable=False),
    sa.Column('vheicle_insurance', sa.String(), nullable=True),
    sa.Column('truck_current_location', sa.String(), nullable=False),
    sa.Column('truck_owner_name', sa.String(), nullable=False),
    sa.Column('truck_owner_phone', sa.String(), nullable=False),
    sa.Column('truck_owner_aadhaar', sa.String(), nullable=False),
    sa.Column('truck_owner_pan', sa.String(), nullable=True),
    sa.Column('truck_driver_name', sa.String(), nullable=True),
    sa.Column('truck_driver_phone', sa.String(), nullable=True),
    sa.Column('truck_driver_aadhar', sa.String(), nullable=True),
    sa.Column('truck_driver_license', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tds', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('truck_id'),
    sa.UniqueConstraint('vehicle_registration_number')
    )
    op.create_table('LOAD',
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('pickup_contact_name', sa.String(), nullable=False),
    sa.Column('pickup_contact_phone', sa.String(), nullable=False),
    sa.Column('drop_location', sa.String(), nullable=False),
    sa.Column('drop_datetime', sa.DateTime(), nullable=False),
    sa.Column('drop_contact_name', sa.String(), nullable=False),
    sa.Column('drop_contact_phone', sa.String(), nullable=False),
    sa.Column('load_type', sa.String(), nullable=False),
    sa.Column('load_weight', sa.Float(), nullable=False),
    sa.Column('load_details', sa.String(), nullable=True),
    sa.Column('load_current_location', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['TRUCK.truck_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('load_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LOAD')
    op.drop_table('TRUCK')
    op.drop_table('USER')
    # ### end Alembic commands ###
